name: Tests

on: [pull_request]

jobs:
  ui-tests:
    name: Jest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install packages
        run: npx yarn --frozen-lockfile

      - name: Run tests
        run: npm run test:coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
