name: Tests

on: [pull_request]

jobs:
  cypress-run:
    name: Cypress Tests
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          record: true
          headless: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  ui-tests:
    name: Jest UI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          CI: true
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Run tests
        run: npm run test:coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  api-tests:
    name: Jest API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci
        working-directory: ./api

      - name: Run tests
        run: npx jest
        working-directory: ./api
        env:
          MUX_TOKEN_ID: nada
          MUX_TOKEN_SECRET: nada

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
